name: Update filters

on:
  push:
    branches:
      - master

concurrency:
  group: update-filters
  cancel-in-progress: true

jobs:
  update-filters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: generator
        run: npm install

      - name: Generate filters
        working-directory: generator
        run: npm run build

      - name: Compute current MD5 of modes configuration
        id: compute-md5
        run: |
          md5sum generator/configuration/modes.json > .github/filters-comparison-md5-new
          if [ -f .github/filters-comparison-md5 ]; then
            cmp --silent .github/filters-comparison-md5 .github/filters-comparison-md5-new && echo "No changes in configuration." && exit 0
          fi
          echo "Configuration changed, proceeding with table generation."

      - name: Install chromium
        if: steps.compute-md5.outcome == 'success'
        working-directory: generator
        run: npx playwright install --with-deps

      - name: Generate table image
        if: steps.compute-md5.outcome == 'success'
        working-directory: generator
        run: npm run build:table

      - name: Update current MD5 file of modes configuration
        if: steps.compute-md5.outcome == 'success'
        run: mv .github/filters-comparison-md5-new .github/filters-comparison-md5

      - name: Commit and push updated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add *.filter
          git add .github/filters-comparison-md5
          git add .github/filters-comparison.png

          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping commit step.";
            exit 0;
          fi

          git commit -m "Filters updated after merge"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
